# Generated by Django 5.0.2 on 2024-02-17 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_history', '0002_initial'),
        ('studies_medicals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesmedicals',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studiesmedicals',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_history.medicalhistory'),
        ),
        migrations.AddField(
            model_name='studiesmedicals',
            name='tipy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies_medicals.typestudiemedical'),
        ),
    ]
